[project]
name = "datacommons-test-agents"
dynamic = ["version"]
description = "Data Commons Test Agents"
readme = "README.md"
requires-python = ">=3.11,<3.13"
dependencies = [
    "google-adk",
    "google-adk[eval]",
    "datacommons-mcp",
]
urls = {Homepage = "https://github.com/datacommonsorg/agent-toolkit"}

[build-system]
requires = ["uv", "setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
datacommons_test_agents = ["*.json"]

[tool.setuptools.dynamic]
version = {attr = "datacommons_test_agents.version.__version__"}
