# Copyright 2025 Google LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

steps:
  # 1. Install uv and build tools
  - name: python:3.12-slim
    entrypoint: bash
    args:
      - -c
      - |
        pip install uv
        # Generate dynamic version and update version.py
        # Use python script to get next sequential dev version from TestPyPI
        new_version=$(python3 scripts/get_next_version.py --type dev)
        echo "$new_version" > _version.txt
        echo "Generated version: $new_version"
        sed -i 's/^version = ".*"/version = "'$new_version'"/' packages/datacommons-mcp/pyproject.toml

        # Build and Publish
        cd packages/datacommons-mcp
        uv build --out-dir dist
        uv publish --publish-url https://test.pypi.org/legacy/ --token $$TEST_PYPI_TOKEN
    secretEnv: ['TEST_PYPI_TOKEN']

  # 2. Wait for TestPyPI propagation
  - name: python:3.12-slim
    entrypoint: bash
    args:
    - -c
    - |
      pip install certifi
      python3 scripts/wait_for_pypi.py datacommons-mcp $(cat _version.txt) --repository https://test.pypi.org/simple

  # 3. Build Container Image
  - name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - |
        docker build \
          --build-arg MCP_VERSION=$(cat _version.txt) \
          --build-arg PIP_INDEX_URL=https://pypi.org/simple/ \
          --build-arg PIP_EXTRA_INDEX_URL=https://test.pypi.org/simple/ \
          -t gcr.io/$PROJECT_ID/datacommons-mcp-server:autopush \
          -t gcr.io/$PROJECT_ID/datacommons-mcp-server:autopush-$(cat _version.txt) .
        docker push gcr.io/$PROJECT_ID/datacommons-mcp-server:autopush
        docker push gcr.io/$PROJECT_ID/datacommons-mcp-server:autopush-$(cat _version.txt)

  # 4. Deploy to Cloud Run
  # NOTE: Using prod search root because autopush search root (autopush.datacommons.org) requires a Google login.
  # The search root will completely go away once we start using the new resolve endpoint.
  # TODO: Remove this once we start using the new resolve endpoint.
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        gcloud run deploy mcp-server-autopush \
        --image=gcr.io/$PROJECT_ID/datacommons-mcp-server:autopush \
        --region=us-central1 \
        --platform=managed \
        --no-allow-unauthenticated \
        --set-env-vars=MCP_VERSION=$(cat _version.txt) \
        --set-env-vars=DC_API_ROOT=https://autopush.api.datacommons.org/v2 \
        --set-env-vars=DC_SEARCH_ROOT=https://datacommons.org \
        --set-env-vars=DC_API_KEY_VALIDATION_ROOT=https://autopush.api.datacommons.org \
        --set-secrets=DC_API_KEY=dc-autopush-api-key-for-mcp:latest \
        --service-account=datacommons-mcp-server@datcom-mixer-autopush.iam.gserviceaccount.com \
        --project=datcom-mixer-autopush

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/TEST_PYPI_TOKEN/versions/latest
    env: 'TEST_PYPI_TOKEN'

options:
  logging: CLOUD_LOGGING_ONLY
